# Generated by Django 5.0.7 on 2024-07-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_remove_profesor_curso_alumno_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
