# Generated by Django 5.0.7 on 2024-07-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_alumno_precio_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='precio_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
