# Generated by Django 5.0.7 on 2024-07-23 02:16

import inscripciones.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_alter_alumno_precio_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tipo_descto',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='vacacion',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='monto_descto',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[inscripciones.validators.validar_descto]),
        ),
    ]
