# Generated by Django 5.0.7 on 2024-07-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_remove_alumno_monto_pagado_remove_alumno_tipo_descto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='precio_hora',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
