# Generated by Django 5.0.7 on 2024-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_alter_alumno_monto_total_alter_alumno_precio_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('inf', 'Infantil'), ('adt', 'Adulto')], default='adt', max_length=3),
        ),
    ]
